// Generated by CIRCT firtool-1.62.0
module Adder(
  input        clock,
  input        reset,
  input  [1:0] io_a,
  input  [1:0] io_b,
  output [1:0] io_c
);

  reg [1:0] reg_0;
  always @(posedge clock)
    reg_0 <= io_a + io_b;
  assign io_c = reg_0;
endmodule

