// Generated by CIRCT firtool-1.62.0
module Const(
  input        clock,
  input        reset,
  input  [7:0] io_input,
  output [7:0] io_outSum,
  output [7:0] io_outAnd,
  output [7:0] io_outOr,
  output [7:0] io_outXor
);

  reg  [7:0] io_outSum_REG;
  reg  [7:0] io_outAnd_REG;
  reg  [7:0] io_outOr_REG;
  reg  [7:0] io_outXor_REG;
  wire [7:0] _d_T = io_input + 8'h2A;
  always @(posedge clock) begin
    io_outSum_REG <= io_input + 8'h39;
    io_outAnd_REG <= _d_T & 8'hAA;
    io_outOr_REG <= _d_T | 8'hAA;
    io_outXor_REG <= _d_T ^ 8'hAA;
  end // always @(posedge)
  assign io_outSum = io_outSum_REG;
  assign io_outAnd = io_outAnd_REG;
  assign io_outOr = io_outOr_REG;
  assign io_outXor = io_outXor_REG;
endmodule

