// Generated by CIRCT firtool-1.62.0
module Counter(
  input        clock,
  input        reset,
  input        io_start,
  output [1:0] io_out
);

  reg [1:0] cntr;
  always @(posedge clock) begin
    if (reset)
      cntr <= 2'h0;
    else
      cntr <= cntr + 2'h1;
  end // always @(posedge)
  assign io_out = cntr;
endmodule
