// Generated by CIRCT firtool-1.62.0
module Fir(
  input        clock,
               reset,
  input  [3:0] io_in,
  input        io_valid,
  output [3:0] io_out,
  input  [3:0] io_consts_0,
               io_consts_1,
               io_consts_2,
               io_consts_3
);

  reg [3:0] taps_1;
  reg [3:0] taps_2;
  reg [3:0] taps_3;
  always @(posedge clock) begin
    if (reset) begin
      taps_1 <= 4'h0;
      taps_2 <= 4'h0;
      taps_3 <= 4'h0;
    end
    else if (io_valid) begin
      taps_1 <= io_in;
      taps_2 <= taps_1;
      taps_3 <= taps_2;
    end
  end // always @(posedge)
  assign io_out =
    io_in * io_consts_0 + taps_1 * io_consts_1 + taps_2 * io_consts_2 + taps_3
    * io_consts_3;
endmodule

