// Generated by CIRCT firtool-1.62.0
// VCS coverage exclude_file
module mem_8x8(
  input  [2:0] R0_addr,
  input        R0_en,
  input        R0_clk,
  output [7:0] R0_data,
  input  [2:0] W0_addr,
  input        W0_en,
  input        W0_clk,
  input  [7:0] W0_data
);

  reg [7:0] Memory[0:7];
  reg       _R0_en_d0;
  reg [2:0] _R0_addr_d0;
  always @(posedge R0_clk) begin
    _R0_en_d0 <= R0_en;
    _R0_addr_d0 <= R0_addr;
  end // always @(posedge)
  always @(posedge W0_clk) begin
    if (W0_en & 1'h1)
      Memory[W0_addr] <= W0_data;
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 8'bx;
endmodule

module SyncReadMemTest(
  input        clock,
  input        reset,
  input        io_ren,
  input        io_wen,
  input  [2:0] io_raddr,
  input  [2:0] io_waddr,
  input  [1:0] io_wdata_0,
  input  [1:0] io_wdata_1,
  input  [1:0] io_wdata_2,
  input  [1:0] io_wdata_3,
  output [1:0] io_rdata_0,
  output [1:0] io_rdata_1,
  output [1:0] io_rdata_2,
  output [1:0] io_rdata_3
);

  wire [7:0] _mem_ext_R0_data;
  mem_8x8 mem_ext (
    .R0_addr (io_raddr),
    .R0_en   (io_ren),
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .W0_addr (io_waddr),
    .W0_en   (io_wen),
    .W0_clk  (clock),
    .W0_data ({io_wdata_3, io_wdata_2, io_wdata_1, io_wdata_0})
  );
  assign io_rdata_0 = _mem_ext_R0_data[1:0];
  assign io_rdata_1 = _mem_ext_R0_data[3:2];
  assign io_rdata_2 = _mem_ext_R0_data[5:4];
  assign io_rdata_3 = _mem_ext_R0_data[7:6];
endmodule

