// Generated by CIRCT firtool-1.62.0
// VCS coverage exclude_file
module mem_1024x32(
  input  [9:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [31:0] R0_data,
  input  [9:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [31:0] W0_data,
  input  [3:0]  W0_mask
);

  reg [31:0] Memory[0:1023];
  reg        _R0_en_d0;
  reg [9:0]  _R0_addr_d0;
  always @(posedge R0_clk) begin
    _R0_en_d0 <= R0_en;
    _R0_addr_d0 <= R0_addr;
  end // always @(posedge)
  always @(posedge W0_clk) begin
    if (W0_en & W0_mask[0])
      Memory[W0_addr][32'h0 +: 8] <= W0_data[7:0];
    if (W0_en & W0_mask[1])
      Memory[W0_addr][32'h8 +: 8] <= W0_data[15:8];
    if (W0_en & W0_mask[2])
      Memory[W0_addr][32'h10 +: 8] <= W0_data[23:16];
    if (W0_en & W0_mask[3])
      Memory[W0_addr][32'h18 +: 8] <= W0_data[31:24];
  end // always @(posedge)
  assign R0_data = _R0_en_d0 ? Memory[_R0_addr_d0] : 32'bx;
endmodule

module SyncReadMemTest(
  input        clock,
  input        reset,
  input        io_enable,
  input        io_write,
  input  [9:0] io_addr,
  input        io_mask_0,
  input        io_mask_1,
  input        io_mask_2,
  input        io_mask_3,
  input  [7:0] io_dataIn_0,
  input  [7:0] io_dataIn_1,
  input  [7:0] io_dataIn_2,
  input  [7:0] io_dataIn_3,
  output [7:0] io_dataOut_0,
  output [7:0] io_dataOut_1,
  output [7:0] io_dataOut_2,
  output [7:0] io_dataOut_3
);

  wire [31:0] _mem_ext_R0_data;
  mem_1024x32 mem_ext (
    .R0_addr (io_addr),
    .R0_en   (io_enable),
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .W0_addr (io_addr),
    .W0_en   (1'h1),
    .W0_clk  (clock),
    .W0_data ({io_dataIn_3, io_dataIn_2, io_dataIn_1, io_dataIn_0}),
    .W0_mask ({io_mask_3, io_mask_2, io_mask_1, io_mask_0})
  );
  assign io_dataOut_0 = _mem_ext_R0_data[7:0];
  assign io_dataOut_1 = _mem_ext_R0_data[15:8];
  assign io_dataOut_2 = _mem_ext_R0_data[23:16];
  assign io_dataOut_3 = _mem_ext_R0_data[31:24];
endmodule

