top := "Adder"
vcd_file := "hello.vcd"
dir := "../examples/digitaltop"
vcd        := dir + "/" + vcd_file
svfile     := dir + "/" + top + ".sv"
input_file := dir + "/" + top + ".input"
lut_file   := dir + "/" + top + ".lut.blif"
sim_dir    := "sim-dir-" + top
instance_path := ""

time_steps_per_cycle := "5"
ref_skip_cycles := "200"
check_cycle_period := "1"

num_mods := "17"
num_procs := "64"
sram_width := "256"
sram_entries := "16384"
max_steps := "1024"

imem_lat := "1"
inter_mod_nw_lat := "1"
inter_proc_nw_lat := "1"
dmem_rd_lat := "0"
dmem_wr_lat := "1"

[group: 'clean']
clean:
  rm -rf sim-dir-*
  rm -rf blif-sim-dir-*
  rm DEBUG*

[group: 'test']
test $RUST_TEST_THREADS="1":
  cargo test --release --verbose | tee DEBUG

[group: 'echo']
echo:
  echo {{top}}
  echo {{svfile}}
  echo {{input_file}}
  echo {{instance_path}}

[group: 'run']
run_measure_utilization $RUST_BACKTRACE="1":
  cargo run --release \
    --bin run_measure_utilization \
    -- --sv-file-path {{svfile}}  \
       -b {{lut_file}} \
       -t {{top}} \
       --num-mods {{num_mods}} \
       --num-procs {{num_procs}} \
       --sram-width {{sram_width}} \
       --sram-entries {{sram_entries}} \
       --imem-lat {{imem_lat}} \
       --dmem-rd-lat {{dmem_rd_lat}} \
       --dmem-wr-lat {{dmem_wr_lat}} \
       --inter-proc-nw-lat {{inter_proc_nw_lat}} \
       --inter-mod-nw-lat {{inter_mod_nw_lat}} \
       --max-steps {{max_steps}} \
       --instance-path {{instance_path}} | tee DEBUG

[group: 'run']
run_test_gen_from_vcd $RUST_BACKTRACE="1":
  cargo run --release \
    --bin run_test_gen_from_vcd \
    -- --vcd {{vcd}} \
       --sv-file-path {{svfile}}  \
       --top-mod {{top}} \
       --instance-path {{instance_path}} \
       --output {{input_file}} \
       --clock-start-low \
       --timesteps-per-cycle {{time_steps_per_cycle}} \
       --ref-skip-cycles {{ref_skip_cycles}} | tee DEBUG

[group: 'run']
bee_vcd $RUST_BACKTRACE="1":
  cargo run --release \
    --bin bee \
    -- -s {{svfile}} \
       -t {{top}} \
       -i {{input_file}} \
       -b {{lut_file}} \
       --vcd {{vcd}} \
       --num-mods {{num_mods}} \
       --num-procs {{num_procs}} \
       --sram-width {{sram_width}} \
       --sram-entries {{sram_entries}} \
       --imem-lat {{imem_lat}} \
       --dmem-rd-lat {{dmem_rd_lat}} \
       --dmem-wr-lat {{dmem_wr_lat}} \
       --inter-proc-nw-lat {{inter_proc_nw_lat}} \
       --inter-mod-nw-lat {{inter_mod_nw_lat}} \
       --max-steps {{max_steps}} \
       --instance-path {{instance_path}} \
       --ref-skip-cycles {{ref_skip_cycles}} \
       --clock-start-low \
       --timesteps-per-cycle {{time_steps_per_cycle}} \
       --sim-dir {{sim_dir}} \
       --check-cycle-period {{check_cycle_period}} | tee DEBUG-BEE-VCD

[group: 'run']
bee $RUST_BACKTRACE="1":
  cargo run --release \
    --bin bee \
    -- -s {{svfile}} \
       -t {{top}} \
       -i {{input_file}} \
       -b {{lut_file}} \
       --num-mods {{num_mods}} \
       --num-procs {{num_procs}} \
       --sram-width {{sram_width}} \
       --sram-entries {{sram_entries}} \
       --imem-lat {{imem_lat}} \
       --dmem-rd-lat {{dmem_rd_lat}} \
       --dmem-wr-lat {{dmem_wr_lat}} \
       --inter-proc-nw-lat {{inter_proc_nw_lat}} \
       --inter-mod-nw-lat {{inter_mod_nw_lat}} \
       --max-steps {{max_steps}} \
       --sim-dir {{sim_dir}} \
       --check-cycle-period {{check_cycle_period}} | tee DEBUG-BEE

[group: 'run']
run_blifsim $RUST_BACKTRACE="1":
  cargo run --release \
    --bin run_blifsim \
    -- -s {{svfile}} \
       -t {{top}} \
       -i {{input_file}} \
       -b {{lut_file}} \
       --num-mods {{num_mods}} \
       --num-procs {{num_procs}} \
       --sram-width {{sram_width}} \
       --sram-entries {{sram_entries}} \
       --imem-lat {{imem_lat}} \
       --dmem-rd-lat {{dmem_rd_lat}} \
       --dmem-wr-lat {{dmem_wr_lat}} \
       --inter-proc-nw-lat {{inter_proc_nw_lat}} \
       --inter-mod-nw-lat {{inter_mod_nw_lat}} \
       --sim-dir {{sim_dir}} \
       --max-steps {{max_steps}} | tee DEBUG-BLIFSIM
